project:
  type: manuscript

execute:
  freeze: auto

format:
  elsevier-html:
    toc: true
    comments:
      hypothesis: false
  docx:
    reference-doc: custom-reference-doc.docx
    link-citations: true
    link-bibliography: true
  jats: default
  elsevier-pdf: default

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure

